apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: depcop25
  name: depcop25
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depcop25
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: depcop25
    spec:
      containers:
      - image: sab22/cop25:5
        name: php
        ports:
        - containerPort: 80
        resources: {}
status: {}
