
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cop25
  name: cop25
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cop25
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cop25
    spec:
      containers:
      - image: sab22/cop25:5
        name: image
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

