apiVersion: apps/v1
kind: Deployment
metadata:
  name: cop22
spec:
  selector:
    matchLabels:
      app: cop2
  replicas: 1
  template:
    metadata:
      labels:
        app: cop22
    spec:
      containers:
      - name: cop22
        image: sab22/cop25:5
        ports:
        - containerPort: 80
