apiVersion: apps/v1
kind: Deployment
metadata:
  name: cop252
spec:
  selector:
    matchLabels:
      app: cop252
  replicas: 1
  template:
    metadata:
      labels:
        app: cop252
    spec:
      containers:
      - name: cop252
        image: sab22/cop25:5
        ports:
        - containerPort: 80
